### ISSUE TITLE
Can not add items to list

### ISSUE THREAD

**Issue by arixking** [philipwking/simple-to-do#1]
Steps to reproduce:
1. Type something
2. Press enter

Result: 
Blank

System Specs:
Macbook Pro (2018)
macOS Catalina (10.15)

![Screen Shot 2020-01-31 at 10 26 34 AM](https://user-images.githubusercontent.com/42951448/73551509-820ac500-4414-11ea-8ded-6d8df860fab1.png)

**Comment by twist295** [comment]
I also have this issue
